# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# TimeOfConcentration.py
# Created on: 2020-12-10 15:37:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy
# overwriting
arcpy.env.overwriteOutput = True

# Local variables:
Use_Input_Features_for_Clipping_Geometry = "false"
design_road_1_Project_Clip = r"D:\6th_sem\final_year\arcGIS\arcpy_currentWS.gdb\design_road_1_Project_Clip"
contributing_area = r"D:\6th_sem\final_year\arcGIS\area_calculation.gdb\contributing_area"
design_road_1_Project_Clip_C = "D:\\6th_sem\\final_year\\arcGIS\\arcpy_currentWS.gdb\\design_road_1_Project_Clip_C" # save location
design_road_1_Project_Clip_G = r"D:\6th_sem\final_year\arcGIS\arcpy_currentWS.gdb\design_road_1_Project_Clip_G" #point
contributing_area__3_ = design_road_1_Project_Clip_G
contributing_area__2_ = r"D:\6th_sem\final_year\arcGIS\area_calculation.gdb\contributing_area"
contributing_area_PolygonToL = "D:\\6th_sem\\final_year\\arcGIS\\arcpy_currentWS.gdb\\contributing_area_PolygonToL"
contributing_area_PolygonToL1 = "D:\\6th_sem\\final_year\\arcGIS\\arcpy_currentWS.gdb\\contributing_area_PolygonToL1"
designasd = "D:\\6th_sem\\final_year\\arcGIS\\arcpy_currentWS.gdb\\designasd"

# Process: Clip (2)
arcpy.Clip_analysis(design_road_1_Project_Clip, contributing_area, design_road_1_Project_Clip_C, "")

# make feature layer
arcpy.MakeFeatureLayer_management(contributing_area__2_,"contributing_area__2_lyr")


# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management("contributing_area__2_lyr", "INTERSECT", design_road_1_Project_Clip_G, "", "NEW_SELECTION", "NOT_INVERT")

# Process: Polygon To Line
arcpy.PolygonToLine_management("contributing_area__2_lyr", contributing_area_PolygonToL, "IGNORE_NEIGHBORS")

# Process: Generate Points Along Lines
arcpy.GeneratePointsAlongLines_management(contributing_area_PolygonToL, contributing_area_PolygonToL1, "PERCENTAGE", "", "5", "END_POINTS")

# Process: Point Distance
arcpy.PointDistance_analysis(design_road_1_Project_Clip_G, contributing_area_PolygonToL1, designasd, "")

